export const FETCH_IMAGES = "FETCH_IMAGES";
export const SELECT_IMAGE = "SELECT_IMAGE";
export const REMOVE_SELECTED_IMAGE = "REMOVE_SELECTED_IMAGE";
export const UPDATE_ACTIVE_IMAGE = "UPDATE_ACTIVE_IMAGE";
